name: earnly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  cherry_toast: ^1.13.0
  get: ^4.7.3
  google_fonts: ^6.3.2
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.4
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_1.png
    - assets/images/logo_2.png
    - assets/images/background_1.png
    - assets/images/background_2.png
    - assets/images/crypto_coin.png
    - assets/images/crypto_coins.png
    - assets/images/profile.png
    - assets/images/ludo.png
    - assets/images/dice.png
    - assets/images/wheel.png
    - assets/images/coinbase.png
    - assets/images/transfer.png
    - assets/images/chart.png


