name: earnly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_1.png
    - assets/images/logo_2.png
    - assets/images/background_1.png
    - assets/images/background_2.png
    - assets/images/crypto_coin.png
    - assets/images/crypto_coins.png
    - assets/images/profile.png
    - assets/images/ludo.png
    - assets/images/dice.png
    - assets/images/wheel.png
    - assets/images/coinbase.png
    - assets/images/transfer.png
    - assets/images/chart.png


